### ISSUE TITLE
Crashing at enter filepath

### ISSUE THREAD

**Issue by dallasco** [rainbowpigeon/sublime-text-4-patcher#10]
I may be missing something, but after entering the file path the terminal window closes and does nothing. Sublime build 4126

**Comment by ghost** [comment]
Could you show me a screenshot of your input as well as the script's output?

**Comment by dallasco** [comment]
![Capture](https://user-images.githubusercontent.com/25357605/153693685-97914e4d-b499-4318-9927-4a1c3642adf5.PNG)
![Capture2](https://user-images.githubusercontent.com/25357605/153693689-4ef59f52-df77-47f0-9685-45a4031105be.PNG)

Tried both ways, and again I'm not familiar with python so it's probably user error. But immediately after hitting enter the window closes giving no feedback

**Comment by ghost** [comment]
The window immediately closes because of the way you're launching Python scripts: if I understand correctly you're double-clicking on the `sublime_text_4_patcher.py` file to launch it right?

Generally to use Python scripts we first open a terminal (so `cmd.exe` in your case of Windows), then change the directory to where the script resides with `cd`, and finally run the command `python sublime_text_4_patcher.py` or `python3 sublime_text_4_patcher.py`. This way, after the script executes, the terminal window will still be open and the script's output will remain on the screen.

One more thing to note: since your `sublime_text.exe` is located in `C:\Program Files\`, you might need to launch your terminal (`cmd.exe`) as an Administrator so that there is sufficient privileges to write to that directory. If not, you can copy out `sublime_text.exe` to some other directory like your Desktop, patch it there, then move it back to `C:\Program Files\`.

Oh yeah and your second way of input is correct (the one that includes `sublime_text.exe` in the file path).

**Comment by dallasco** [comment]
That's exactly what I was doing. Working perfectly now, thanks for your help.
