### ISSUE TITLE
0x000A65C7

### ISSUE THREAD

**Issue by k3nnk3nn** [rainbowpigeon/sublime-text-4-patcher#5]
Why you patch 0x000A65C7 with 48 31 C0 C3 for windows ? shouldn't it only be patched with C3 ?

**Comment by ghost** [comment]
This is for the license_notify thread correct? I originally followed leogx9r's guidance to patch it with a return 0 (`48 31 C0 C3`), but as it turns out the return value does not really matter since it is apparently not used anywhere. So both works.

![image](https://user-images.githubusercontent.com/16717153/137824064-1458be33-93f6-43cf-a8b4-7a97d37233e8.png)

**Comment by k3nnk3nn** [comment]
Thank you for the explanation
